project:
  type: website
  output-dir: docs

website:
  title: "Language, Cognition, and Computation Lab"
  navbar:
    logo: images/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      # - text: "Publications"
      #   href: publications.qmd
      - text: "People"
        href: people.qmd
      - text: "Join"
        href: join.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false